### ISSUE TITLE
DestroyAll only works if CreateAll or LoadState were called first

### ISSUE THREAD

**Issue by catsby** [hashicorp/waypoint-plugin-sdk#37]
[DestroyAll](https://github.com/hashicorp/waypoint-plugin-sdk/blob/6834347d5971dfcd86521628681689012933624a/framework/resource/manager.go#L228) checks for `Order` or `createState` to be set before attempting to destroy anything, which are only(?) set when `CreateAll` (or `LoadState`) is called first. I _believe_ this prevents "manual" cleanup like seen in [docker/platform.go](https://github.com/hashicorp/waypoint/blob/fbc91adf67a79fbbe3f167e61fd9a739549f57fd/builtin/docker/platform.go#L529-L543) and [k8s/platform.go](https://github.com/hashicorp/waypoint/blob/fbc91adf67a79fbbe3f167e61fd9a739549f57fd/builtin/k8s/platform.go#L634-L648). I attempt to replicate this style of deleting resources by setting their state in https://github.com/hashicorp/waypoint/pull/1648 but the corresponding `Destroy` methods are never called

**Comment by mitchellh** [comment]
This should be easy to write a unit test for. 

We need state to do a destroy, so it makes sense state needs to be set. But if there are cases you can set state and destroy still isn't called, then its definitely a bug.

**Comment by catsby** [comment]
@mitchellh I _believe_ https://github.com/hashicorp/waypoint-plugin-sdk/pull/38 reproduces this.

**Comment by catsby** [comment]
Mitchell mentioned he wanted to look into this so I'm going to un-assign myself at this time.
